src/Entity/AnoLectivo.php
<?php

namespace App\Entity;

use App\Repository\AnoLectivoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnoLectivoRepository::class)
 */
class AnoLectivo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nome_ano_lectivo;

    /**
     * @ORM\Column(type="date")
     */
    private $data_inicio;

    /**
     * @ORM\OneToMany(targetEntity=Curso::class, mappedBy="anoLectivo")
     */
    private $curso;

    public function __construct()
    {
        $this->curso = new ArrayCollection();
        $this->data_inicio = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomeAnoLectivo(): ?string
    {
        return $this->nome_ano_lectivo;
    }

    public function setNomeAnoLectivo(string $nome_ano_lectivo): self
    {
        $this->nome_ano_lectivo = $nome_ano_lectivo;

        return $this;
    }

    public function getDataInicio(): ?\DateTimeInterface
    {
        return $this->data_inicio;
    }

    public function setDataInicio(\DateTimeInterface $data_inicio): self
    {
        $this->data_inicio = $data_inicio;

        return $this;
    }

    /**
     * @return Collection|Curso[]
     */
    public function getCurso(): Collection
    {
        return $this->curso;
    }

    public function addCurso(Curso $curso): self
    {
        if (!$this->curso->contains($curso)) {
            $this->curso[] = $curso;
            $curso->setAnoLectivo($this);
        }

        return $this;
    }

    public function removeCurso(Curso $curso): self
    {
        if ($this->curso->removeElement($curso)) {
            // set the owning side to null (unless already changed)
            if ($curso->getAnoLectivo() === $this) {
                $curso->setAnoLectivo(null);
            }
        }

        return $this;
    }

    public function __toString(){
        return $this->nome_ano_lectivo;
    }
}

src/Form/AnoLectivoType.php
<?php

namespace App\Form;

use App\Entity\AnoLectivo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnoLectivoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nome_ano_lectivo')
            ->add('data_inicio', DateType::class, ['widget'=>'single_text'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AnoLectivo::class,
        ]);
    }
}

src/Controller/Estructura/AnoLectivoController.php
<?php

namespace App\Controller\Estructura;

use App\Entity\AnoLectivo;
use App\Form\AnoLectivoType;
use App\Repository\AnoLectivoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ano/lectivo")
 */
class AnoLectivoController extends AbstractController
{
    /**
     * @Route("/", name="ano_lectivo_index", methods={"GET"})
     */
    public function index(AnoLectivoRepository $anoLectivoRepository): Response
    {
        return $this->render('ano_lectivo/index.html.twig', [
            'ano_lectivos' => $anoLectivoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ano_lectivo_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $anoLectivo = new AnoLectivo();
        $form = $this->createForm(AnoLectivoType::class, $anoLectivo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($anoLectivo);
            $entityManager->flush();

            return $this->redirectToRoute('ano_lectivo_index');
        }

        return $this->render('ano_lectivo/new.html.twig', [
            'ano_lectivo' => $anoLectivo,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ano_lectivo_show", methods={"GET"})
     */
    public function show(AnoLectivo $anoLectivo): Response
    {
        return $this->render('ano_lectivo/show.html.twig', [
            'ano_lectivo' => $anoLectivo,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ano_lectivo_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, AnoLectivo $anoLectivo): Response
    {
        $form = $this->createForm(AnoLectivoType::class, $anoLectivo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ano_lectivo_index');
        }

        return $this->render('ano_lectivo/edit.html.twig', [
            'ano_lectivo' => $anoLectivo,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ano_lectivo_delete", methods={"POST"})
     */
    public function delete(Request $request, AnoLectivo $anoLectivo): Response
    {
        if ($this->isCsrfTokenValid('delete'.$anoLectivo->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($anoLectivo);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ano_lectivo_index');
    }
}

templates/ano_lectivo/_delete_form.html.twig
<form method="post" action="{{ path('ano_lectivo_delete', {'id': ano_lectivo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ano_lectivo.id) }}">
    <button class="btn btn-sm btn-danger"><i class="fa-trash-trash"></i> Delete</button>
</form>

templates/ano_lectivo/_form.html.twig
{{ form_start(form) }}
<tr>
    <button class="btn btn-sm btn-success"><i class="la la-save"></i> {{ button_label|default('Guardar') }}</button>
    <a href="{{ path('ano_lectivo_index') }}" class="btn btn-sm btn-primary"><i class="la la-list"></i> Voltar a Lista</a>
</tr>

{{ form_widget(form) }}
{{ form_end(form) }}

templates/ano_lectivo/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Ano Lectivo{% endblock %}

{% block body %}
    <h3>Editar Ano Lectivo</h3>

    {{ include('ano_lectivo/_form.html.twig', {'button_label': 'Actualizar'}) }}


{% endblock %}

templates/ano_lectivo/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}AnoLectivo index{% endblock %}

{% block body %}
<div class="col-lg-8">
    <h3>Lista do Ano Lectivo</h3>

    <a href="{{ path('ano_lectivo_new') }}" class="btn btn-sm btn-primary">Criar Novo</a>

    <div class="card my-2">
        <div class="card-header">
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm mb-0 table-striped">
                    <thead>
            <tr>
                <th class="px-5 py-3">Nome Ano Lectivo</th>
                <th class="py-3">Data Início</th>
                <th class="py-3">Acções</th>
            </tr>
        </thead>
                    <tbody id="customers">
        {% for ano_lectivo in ano_lectivos %}
            <tr class="btn-reveal-trigger">
                <td class="py-2">{{ ano_lectivo.nomeAnoLectivo }}</td>
                <td class="py-2">{{ ano_lectivo.dataInicio ? ano_lectivo.dataInicio|date('Y-m-d') : ''  }}</td>
                <td>
                    <a href="{{ path('ano_lectivo_show', {'id': ano_lectivo.id}) }}" class="btn btn-sm btn-primary"><i class="fas fa-eye"></i></a>
                    <a href="{{ path('ano_lectivo_edit', {'id': ano_lectivo.id}) }}" class="btn btn-sm btn-secondary"><i class="fas fa-edit"></i></a>
                    <a href="{{path('ano_lectivo_delete', {'id': ano_lectivo.id})}}" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/ano_lectivo/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Novo Ano Lectivo{% endblock %}

{% block body %}
    <h3>Criar Novo Ano Lectivo</h3>
<div class="col-md-10">

    {{ include('ano_lectivo/_form.html.twig') }}

</div>

{% endblock %}

templates/ano_lectivo/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mostrar Ano Lectivo{% endblock %}

{% block body %}

<div class="col-sm-8">
    <div class="card">
        <div class="card-header">
            <h4> Ano Lectivo {{ ano_lectivo.nomeAnoLectivo}}</h4>
            <div class="card-body">
                <table class="table table-sm ">
                    <tbody>

                    <tbody>
                    <tr>
                        {{ include('ano_lectivo/_delete_form.html.twig') }}
                        <a href="{{ path('ano_lectivo_index') }}" class="btn btn-sm btn-primary mr-2 ml-2"><i class="fas fa-list"></i>Voltar a Lista</a>
                        <a href="{{ path('ano_lectivo_edit', {'id': ano_lectivo.id}) }}" class="btn btn-sm btn-secondary"><i class="fas fa-edit"></i>Editar</a>

                    </tr>
                    <tr>
                        <th>Nome Ano Lectivo</th>
                        <td>{{ ano_lectivo.nomeAnoLectivo }}</td>
                    </tr>
                    <tr>
                        <th>Data Início</th>
                        <td>{{ ano_lectivo.dataInicio ? ano_lectivo.dataInicio|date('Y-m-d') : '' }}</td>
                    </tr>

                    </tbody>
                </table>

            </div>
        </div>
    </div>

</div>



{% endblock %}