src/Entity/AnoAcademico.php
<?php

namespace App\Entity;

use App\Repository\AnoAcademicoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AnoAcademicoRepository::class)
 */
class AnoAcademico
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $nome_ano_academico;

    /**
     * @ORM\ManyToOne(targetEntity=Curso::class, inversedBy="ano_academicos")
     */
    private $curso;

    /**
     * @ORM\OneToMany(targetEntity=Semestre::class, mappedBy="anoAcademico")
     */
    private $semestres;

    /**
     * @ORM\OneToMany(targetEntity=Turma::class, mappedBy="anoAcademico")
     */
    private $turmas;

    /**
     * @ORM\OneToMany(targetEntity=Estudante::class, mappedBy="anoAcademico")
     */
    private $estudiantes;

    public function __construct()
    {
        $this->semestres = new ArrayCollection();
        $this->estudiantes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomeAnoAcademico(): ?string
    {
        return $this->nome_ano_academico;
    }

    public function setNomeAnoAcademico(string $nome_ano_academico): self
    {
        $this->nome_ano_academico = $nome_ano_academico;

        return $this;
    }

    public function getCurso(): ?Curso
    {
        return $this->curso;
    }

    public function setCurso(?Curso $curso): self
    {
        $this->curso = $curso;

        return $this;
    }

    public function __toString(){
            return $this->getcurso().' - '. $this->nome_ano_academico ;
    }

    /**
     * @return Collection|Turma[]
     */
    public function getTurmas(): Collection
    {
        return $this->turmas;
    }

    public function addTurma(Turma $turma): self
    {
        if (!$this->turmas->contains($turma)) {
            $this->turmas[] = $turma;
            $turma->setAnoAcademico($this);
        }

        return $this;
    }

    public function removeTurma(Turma $turma): self
    {
        if ($this->turmas->removeElement($turma)) {
            // set the owning side to null (unless already changed)
            if ($turma->getAnoAcademico() === $this) {
                $turma->setAnoAcademico(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Estudante[]
     */
    public function getEstudiantes(): Collection
    {
        return $this->estudiantes;
    }

    public function addEstudiante(Estudante $estudiante): self
    {
        if (!$this->estudiantes->contains($estudiante)) {
            $this->estudiantes[] = $estudiante;
            $estudiante->setAnoAcademico($this);
        }

        return $this;
    }

    public function removeEstudiante(Estudante $estudiante): self
    {
        if ($this->estudiantes->removeElement($estudiante)) {
            // set the owning side to null (unless already changed)
            if ($estudiante->getAnoAcademico() === $this) {
                $estudiante->setAnoAcademico(null);
            }
        }

        return $this;
    }

}

src/Form/AnoAcademicoType.php
<?php

namespace App\Form;

use App\Entity\AnoAcademico;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AnoAcademicoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nome_ano_academico', ChoiceType::class, ['label'=>'Ano Acadêmico',
                'choices'  => array(
                    '1º' => '1º',
                    '2º' => '2º',
                    '3º' => '3º',
                    '4º' => '4º',
                    '5º' => '5º',
                )
            ])
            ->add('curso')
        ;
    }






    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => AnoAcademico::class,
        ]);
    }
}

src/Controller/Estructura/AnoAcademicoController.php
<?php

namespace App\Controller\Estructura;

use App\Entity\AnoAcademico;
use App\Form\AnoAcademicoType;
use App\Repository\AnoAcademicoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/ano/academico")
 */
class AnoAcademicoController extends AbstractController
{
    /**
     * @Route("/", name="ano_academico_index", methods={"GET"})
     */
    public function index(AnoAcademicoRepository $anoAcademicoRepository): Response
    {
        return $this->render('ano_academico/index.html.twig', [
            'ano_academicos' => $anoAcademicoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="ano_academico_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $anoAcademico = new AnoAcademico();
        $form = $this->createForm(AnoAcademicoType::class, $anoAcademico);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($anoAcademico);
            $entityManager->flush();

            return $this->redirectToRoute('ano_academico_index');
        }

        return $this->render('ano_academico/new.html.twig', [
            'ano_academico' => $anoAcademico,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ano_academico_show", methods={"GET"})
     */
    public function show(AnoAcademico $anoAcademico): Response
    {
        return $this->render('ano_academico/show.html.twig', [
            'ano_academico' => $anoAcademico,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="ano_academico_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, AnoAcademico $anoAcademico): Response
    {
        $form = $this->createForm(AnoAcademicoType::class, $anoAcademico);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('ano_academico_index');
        }

        return $this->render('ano_academico/edit.html.twig', [
            'ano_academico' => $anoAcademico,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="ano_academico_delete", methods={"POST"})
     */
    public function delete(Request $request, AnoAcademico $anoAcademico): Response
    {
        if ($this->isCsrfTokenValid('delete'.$anoAcademico->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($anoAcademico);
            $entityManager->flush();
        }

        return $this->redirectToRoute('ano_academico_index');
    }
}

templates/ano_academico/_delete_form.html.twig
<form method="post" action="{{ path('ano_academico_delete', {'id': ano_academico.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ano_academico.id) }}">
    <button class="btn  btn-sm btn-danger"><i class="la la-trash"></i>Eliminar</button>
</form>

templates/ano_academico/_form.html.twig
{{ form_start(form) }}
<tr>
    <button class="btn btn-sm btn-success"><i class="la la-save"></i> {{ button_label|default('Guardar') }}</button>
    <a href="{{ path('ano_academico_index') }}" class="btn btn-sm btn-primary"><i class="la la-list"></i> Voltar a Lista</a>
</tr>
{{ form_widget(form) }}
{{ form_end(form) }}

templates/ano_academico/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Ano Academico{% endblock %}

{% block body %}
    <h3>Editar Ano Academico</h3>

    {{ include('ano_academico/_form.html.twig', {'button_label': 'Actualizar'}) }}

{% endblock %}

templates/ano_academico/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ano Acadêmico index{% endblock %}

{% block body %}

<div class="mx-auto">
<div class="col-lg-8">
    <h3>Listar Ano Acadêmico</h3>

    <a href="{{ path('ano_academico_new') }}" class="btn btn-sm btn-primary">Criar Novo</a>

    <div class="card my-2">
        <div class="card-header">
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm mb-0 table-striped">
                    <thead>
                    <tr>
                        <th class="px-5 py-3">Nome Ano Acadêmico</th>
                        <th class="py-3">Acções</th>
                    </tr>
                    </thead>
                    <tbody id="customers">
                    {% for ano_academico in ano_academicos %}
                    <tr class="btn-reveal-trigger">
                        <td class="py-2">{{ ano_academico.nomeAnoAcademico }}</td>
                        <td>
                            <a href="{{ path('ano_academico_show', {'id': ano_academico.id}) }}" class="btn btn-sm btn-primary"><i class="fas fa-eye"></i></a>
                            <a href="{{ path('ano_academico_edit', {'id': ano_academico.id}) }}" class="btn btn-sm btn-secondary"><i class="fas fa-edit"></i></a>
                            <a href="{{path('ano_academico_delete', {'id': ano_academico.id})}}" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">no records found</td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>
</div>



{% endblock %}

templates/ano_academico/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Novo Ano Academico{% endblock %}

{% block body %}
    <h3>Criar Novo Ano Academico</h3>
<div class="col-md-10">

    {{ include('ano_academico/_form.html.twig') }}

</div>


{% endblock %}

templates/ano_academico/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mostrar Ano Academico{% endblock %}

{% block body %}
<div class="col-sm-8">
    <div class="card">
        <div class="card-header">

            <h4> Ano Acadêmico {{ ano_academico.nomeAnoAcademico}}</h4>
            <div class="card-body">
                <table class="table table-sm">
                    <tbody>

                    <tbody>
                    <tr>
                        {{ include('ano_academico/_delete_form.html.twig') }}
                        <a href="{{ path('ano_academico_index') }}" class="btn btn-sm btn-primary mr-2 ml-2"><i class="fas fa-list"></i>Voltar a Lista</a>
                        <a href="{{ path('ano_academico_edit', {'id': ano_academico.id}) }}" class="btn btn-sm btn-secondary"><i class="fas fa-edit"></i>Editar</a>
                    </tr>

                    <tr>
                        <th>Nome Ano Acadêmico</th>
                        <td>{{ ano_academico.nomeAnoAcademico}}</td>
                    </tr>


                    </tbody>
                </table>

            </div>
        </div>
    </div>

</div>



{% endblock %}