src/Entity/Estudante.php
<?php

namespace App\Entity;

use App\Repository\EstudianteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
/**
 * @ORM\Entity(repositoryClass=EstudianteRepository::class)
 *  @Vich\Uploadable
 */

class Estudante implements \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $nome_estudiante;


     /**
     * @ORM\ManyToOne(targetEntity=AnoAcademico::class, inversedBy="estudiantes")
     */
     private $anoAcademico;

     /**
      * @ORM\ManyToMany(targetEntity=Turma::class, mappedBy="estudiantes")
      */
     private $turmas;

    /**
     *@var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
     private $Fotografia;

    /**
     * @var File|null
     * @Vich\UploadableField(mapping="estudante_foto", fileNameProperty="Fotografia" )
     *
     */
    private $FotografiaFile;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

     /**
      * @ORM\Column(type="integer")
      */
     private $NumProcesso;

     /**
      * @ORM\Column(type="string", length=50)
      */
     private $email;

     /**
      * @ORM\Column(type="integer")
      */
     private $telefone;

     /**
      * @ORM\Column(type="string", length=50)
      */
     private $BI;

     /**
      * @ORM\Column(type="date")
      */
     private $DataNascimento;

     /**
      * @ORM\Column(type="boolean")
      */
     private $Discapacidade;

     /**
      * @ORM\ManyToMany(targetEntity=Disciplina::class, inversedBy="estudiantes")
      */
     private $dicsiplinas;

     public function __construct()
     {
         $this->turmas = new ArrayCollection();
         $this->dicsiplinas = new ArrayCollection();
     }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomeEstudiante(): ?string
    {
        return $this->nome_estudiante;
    }

    public function setNomeEstudiante(string $nome_estudiante): self
    {
        $this->nome_estudiante = $nome_estudiante;

        return $this;
    }

    public function __toString(){
        return  $this->getanoAcademico().' - '. $this->nome_estudiante ;
    }

    public function getAnoAcademico(): ?AnoAcademico
    {
        return $this->anoAcademico;
    }

    public function setAnoAcademico(?AnoAcademico $anoAcademico): self
    {
        $this->anoAcademico = $anoAcademico;

        return $this;
    }

    /**
     * @return Collection|Turma[]
     */
    public function getTurmas(): Collection
    {
        return $this->turmas;
    }

    public function addTurma(Turma $turma): self
    {
        if (!$this->turmas->contains($turma)) {
            $this->turmas[] = $turma;
            $turma->addEstudiante($this);
        }

        return $this;
    }

    public function removeTurma(Turma $turma): self
    {
        if ($this->turmas->removeElement($turma)) {
            $turma->removeEstudiante($this);
        }

        return $this;
    }

    /**
     * @return null|string
     */
    public function getFotografia(): ?string
    {
        return $this->Fotografia;
    }

    /**
     * @param null|string $Fotografia
     */
    public function setFotografia(?string $Fotografia): void
    {
        $this->Fotografia = $Fotografia;
    }

    /**
     * @return null|File
     */
    public function getFotografiaFile(): ?File
    {
        return $this->FotografiaFile;
    }

    /**
     * @param null|File $FotografiaFile
     *@return Estudante
     */
    public function setFotografiaFile(?File $FotografiaFile): Estudante
    {
        $this->FotografiaFile = $FotografiaFile;
        if ($this->FotografiaFile instanceof UploadedFile){
            $this->updated_at = new \DateTime('now');
        }
        return $this;

    }


    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getNumProcesso(): ?int
    {
        return $this->NumProcesso;
    }

    public function setNumProcesso(int $NumProcesso): self
    {
        $this->NumProcesso = $NumProcesso;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelefone(): ?int
    {
        return $this->telefone;
    }

    public function setTelefone(int $telefone): self
    {
        $this->telefone = $telefone;

        return $this;
    }

    public function getBI(): ?string
    {
        return $this->BI;
    }

    public function setBI(string $BI): self
    {
        $this->BI = $BI;

        return $this;
    }

    public function getDataNascimento(): ?\DateTimeInterface
    {
        return $this->DataNascimento;
    }

    public function setDataNascimento(\DateTimeInterface $DataNascimento): self
    {
        $this->DataNascimento = $DataNascimento;

        return $this;
    }

    public function getDiscapacidade(): ?bool
    {
        return $this->Discapacidade;
    }

    public function setDiscapacidade(bool $Discapacidade): self
    {
        $this->Discapacidade = $Discapacidade;

        return $this;
    }

    /**
     * String representation of object
     * @link https://php.net/manual/en/serializable.serialize.php
     * @return string the string representation of the object or null
     * @since 5.1.0
     */
    public function serialize()
    {
        $this->FotografiaFile = base64_encode($this->FotografiaFile);
    }

    /**
     * Constructs the object
     * @link https://php.net/manual/en/serializable.unserialize.php
     * @param string $serialized <p>
     * The string representation of the object.
     * </p>
     * @return void
     * @since 5.1.0
     */
    public function unserialize($serialized)
    {
        $this->FotografiaFile = base64_decode($this->FotografiaFile);
    }

    /**
     * @return Collection|Disciplina[]
     */
    public function getDicsiplinas(): Collection
    {
        return $this->dicsiplinas;
    }

    public function addDicsiplina(Disciplina $dicsiplina): self
    {
        if (!$this->dicsiplinas->contains($dicsiplina)) {
            $this->dicsiplinas[] = $dicsiplina;
        }

        return $this;
    }

    public function removeDicsiplina(Disciplina $dicsiplina): self
    {
        $this->dicsiplinas->removeElement($dicsiplina);

        return $this;
    }
}

src/Form/ConfirmarMatriculaType.php
<?php

namespace App\Form;

use App\Entity\Curso;
use App\Entity\Estudante;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConfirmarMatriculaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nome_estudiante')
            ->add('dicsiplinas')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Estudante::class,
        ]);
    }
}

src/Controller/ConfirmarMatricula/ConfirmarMatriculaController.php
<?php

namespace App\Controller\ConfirmarMatricula;

use App\Entity\Estudante;
use App\Form\ConfirmarMatriculaType;
use App\Form\MatriculaType;
use App\Repository\EstudianteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/Confirmar")
 */
class ConfirmarMatriculaController extends AbstractController
{
    /**
     * @Route("/", name="Confirmar_index", methods={"GET"})
     */
    public function index(EstudianteRepository $estudianteRepository): Response
    {
        return $this->render('ConfirmarMatricula/index.html.twig', [
            'estudiantes' => $estudianteRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="Confirmar_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $estudiante = new Estudante();
        $form = $this->createForm(ConfirmarMatriculaType::class, $estudiante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($estudiante);
            $entityManager->flush();

            return $this->redirectToRoute('Confirmar_index');
        }

        return $this->render('ConfirmarMatricula/new.html.twig', [
            'estudiante' => $estudiante,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="Confirmar_show", methods={"GET"})
     */
    public function show(Estudante $estudiante): Response
    {
        return $this->render('ConfirmarMatricula/show.html.twig', [
            'estudiante' => $estudiante,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="Confirmar_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Estudante $estudiante): Response
    {
        $form = $this->createForm(ConfirmarMatriculaType::class, $estudiante);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('Confirmar_index');
        }

        return $this->render('ConfirmarMatricula/edit.html.twig', [
            'estudiante' => $estudiante,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="Confirmar_delete", methods={"POST"})
     */
    public function delete(Request $request, Estudante $estudiante): Response
    {
        if ($this->isCsrfTokenValid('delete'.$estudiante->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($estudiante);
            $entityManager->flush();
        }

        return $this->redirectToRoute('Confirmar_index');
    }
}

templates/ConfirmarMatricula/_delete_form.html.twig
<form method="post" action="{{ path('Confirmar_delete', {'id': estudiante.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ estudiante.id) }}">
    <button class="btn btn-sm btn-danger">Eliminar</button>
</form>

templates/ConfirmarMatricula/_form.html.twig
{{ form_start(form) }}
<tr>
    <button class="btn btn-sm btn-success"><i class="la la-save"></i> {{ button_label|default('Guardar') }}</button>
    <a href="{{ path('Confirmar_index') }}" class="btn btn-sm btn-primary"><i class="la la-list"></i> Voltar a Lista</a>
</tr>

{{ form_widget(form) }}

{{ form_end(form) }}

templates/ConfirmarMatricula/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Increver Estudante{% endblock %}

{% block body %}
    <h3>Inscrever Estudante</h3>

    {{ include('ConfirmarMatricula/_form.html.twig', {'button_label': 'Actualiar'}) }}

{% endblock %}

templates/ConfirmarMatricula/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Incrição index{% endblock %}

{% block body %}
<div class="col-lg-12">
    <h3>Listar Inscrição</h3>


    <div class="card my-2">
        <div class="card-header">
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm mb-0 table-striped">
                    <thead>
                    <tr>
                        <th class="px-5 py-3">Nome Estudante</th>
                        <th class="py-3">Num Processo</th>
                        <th class="py-3">BI</th>
                        <th class="py-3">Acções</th>
                    </tr>
                    </thead>
                         </thead>
                    <tbody id="customers">
                    {% for estudiante in estudiantes %}
                        <tr class="btn-reveal-trigger">
                            <td class="py-2">{{estudiante.nomeEstudiante }}</td>
                            <td class="py-2">{{ estudiante.NumProcesso }}</td>
                            <td class="py-2">{{ estudiante.BI }}</td>

                            <td>
                                <a href="{{ path('Confirmar_show', {'id': estudiante.id}) }}" class="btn btn-sm btn-primary"><i class="fas fa-eye"></i></a>
                                <a href="{{ path('Confirmar_edit', {'id': estudiante.id}) }}" class="btn btn-sm btn-secondary"><i class="fas fa-edit"></i>Confirmar Matrícula</a>
                                <a href="{{path('Confirmar_delete', {'id': estudiante.id})}}" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/ConfirmarMatricula/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Inscrever Novo Estudante{% endblock %}

{% block body %}
    <h3>Increver Novo Estudante</h3>
<div class="col-md-10">
    {{ include('ConfirmarMatricula/_form.html.twig') }}
</div>

{% endblock %}

templates/ConfirmarMatricula/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Confirmar Estudante{% endblock %}

{% block body %}



 <div class="col-sm-12">
    <div class="card">
        <div class="card-header">

            <h4> Confirmar {{estudiante.nomeEstudiante}}</h4>
            <div class="card-body">
                <table class="table table-sm ">
                    <tbody>

                    <tbody>
                    <tr>
                        {{ include('ConfirmarMatricula/_delete_form.html.twig') }}
                        <a href="{{ path('Confirmar_index') }}" class="btn btn-sm btn-primary mr-2 ml-2"><i class="fas fa-list"></i>Voltar a Lista</a>
                        <a href="{{ path('Confirmar_edit', {'id': estudiante.id}) }}" class="btn btn-sm btn-secondary"><i class="fas fa-edit"></i>Editar</a>
                    </tr>
                    <tr>
                        <th>Nome Estudante</th>
                        <th>Fotografia</th>
                        <th>Num Processo</th>
                        <th>E-mail</th>
                        <th>Telefone</th>
                        <th>BI</th>
                        <th>Data Nascimento</th>
                        <th>Discapacidade</th>
                    </tr>
                    </thead>
                    <tr>
                        <td>{{ estudiante.nomeEstudiante }}</td>
                        <td>{{ estudiante.Fotografia}}</td>
                        <td>{{ estudiante.NumProcesso }}</td>
                        <td>{{ estudiante.email }}</td>
                        <td>{{ estudiante.telefone  }}</td>
                        <td>{{ estudiante.BI }}</td>
                        <td>{{ estudiante.DataNascimento ? estudiante.DataNascimento|date('Y-m-d') : ''}}</td>
                        <td>{{ estudiante.Discapacidade ? 'Yes' : 'No' }}</td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>

</div>#}



{% endblock %}