src/Entity/Curso.php
<?php

namespace App\Entity;

use App\Repository\CursoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CursoRepository::class)
 */
class Curso
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nome_curso;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Coordinador;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $phone;

    /**
     * @ORM\ManyToOne(targetEntity=AnoLectivo::class, inversedBy="curso")
     */
    private $anoLectivo;

    /**
     * @ORM\OneToMany(targetEntity=AnoAcademico::class, mappedBy="curso")
     */
    private $ano_academicos;

    public function __construct()
    {
        $this->ano_academicos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomeCurso(): ?string
    {
        return $this->nome_curso;
    }

    public function setNomeCurso(string $nome_curso): self
    {
        $this->nome_curso = $nome_curso;

        return $this;
    }

    public function getCoordinador(): ?string
    {
        return $this->Coordinador;
    }

    public function setCoordinador(string $Coordinador): self
    {
        $this->Coordinador = $Coordinador;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAnoLectivo(): ?AnoLectivo
    {
        return $this->anoLectivo;
    }

    public function setAnoLectivo(?AnoLectivo $anoLectivo): self
    {
        $this->anoLectivo = $anoLectivo;

        return $this;
    }

    /**
     * @return Collection|AnoAcademico[]
     */
    public function getAnoAcademicos(): Collection
    {
        return $this->ano_academicos;
    }

    public function addAnoAcademico(AnoAcademico $anoAcademico): self
    {
        if (!$this->ano_academicos->contains($anoAcademico)) {
            $this->ano_academicos[] = $anoAcademico;
            $anoAcademico->setCurso($this);
        }

        return $this;
    }

    public function removeAnoAcademico(AnoAcademico $anoAcademico): self
    {
        if ($this->ano_academicos->removeElement($anoAcademico)) {
            // set the owning side to null (unless already changed)
            if ($anoAcademico->getCurso() === $this) {
                $anoAcademico->setCurso(null);
            }
        }

        return $this;
    }

    public function __toString(){
        return '('. $this->getAnoLectivo().') - '. $this->nome_curso ;
    }
}

src/Form/CursoType.php
<?php

namespace App\Form;

use App\Entity\Curso;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CursoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nome_curso')
            ->add('Coordinador')
            ->add('email')
            ->add('phone')
            ->add('anoLectivo')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Curso::class,
        ]);
    }
}

src/Controller/Estructura/CursoController.php
<?php

namespace App\Controller\Estructura;

use App\Entity\Curso;
use App\Form\CursoType;
use App\Repository\CursoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/curso")
 */
class CursoController extends AbstractController
{
    /**
     * @Route("/", name="curso_index", methods={"GET"})
     */
    public function index(CursoRepository $cursoRepository): Response
    {
        return $this->render('curso/index.html.twig', [
            'cursos' => $cursoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="curso_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $curso = new Curso();
        $form = $this->createForm(CursoType::class, $curso);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($curso);
            $entityManager->flush();

            return $this->redirectToRoute('curso_index');
        }

        return $this->render('curso/new.html.twig', [
            'curso' => $curso,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="curso_show", methods={"GET"})
     */
    public function show(Curso $curso): Response
    {
        return $this->render('curso/show.html.twig', [
            'curso' => $curso,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="curso_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Curso $curso): Response
    {
        $form = $this->createForm(CursoType::class, $curso);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('curso_index');
        }

        return $this->render('curso/edit.html.twig', [
            'curso' => $curso,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="curso_delete", methods={"POST"})
     */
    public function delete(Request $request, Curso $curso): Response
    {
        if ($this->isCsrfTokenValid('delete'.$curso->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($curso);
            $entityManager->flush();
        }

        return $this->redirectToRoute('curso_index');
    }
}

templates/curso/_delete_form.html.twig
<form method="post" action="{{ path('curso_delete', {'id': curso.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ curso.id) }}">
    <button class="btn btn-sm btn-danger"><i class="fa-trash-trash"></i>Eliminar</button>
</form>

templates/curso/_form.html.twig
{{ form_start(form) }}
<tr>
    <button class="btn btn-sm btn-success"><i class="la la-save"></i> {{ button_label|default('Guardar') }}</button>
    <a href="{{ path('curso_index') }}" class="btn btn-sm btn-primary"><i class="la la-list"></i> Voltar a Lista</a>
</tr>

{{ form_widget(form) }}

{{ form_end(form) }}

templates/curso/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editar Curso{% endblock %}

{% block body %}
    <h3>Editar Curso</h3>

    {{ include('curso/_form.html.twig', {'button_label': 'Actualizar'}) }}

{% endblock %}

templates/curso/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Curso index{% endblock %}

{% block body %}
<div class="col-lg-12">
    <h3>Listar Cursos</h3>

    <a href="{{ path('curso_new') }}" class="btn btn-sm btn-primary">Criar Novo</a>

    <div class="card my-2">
        <div class="card-header">
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-sm mb-0 table-striped">
                    <thead>
                    <tr>
                        <th class="px-5 py-3">Nome Curso</th>
                        <th class="py-3">Coordenador</th>
                        <th class="py-3">E-mail</th>
                        <th class="py-3">Telefone</th>
                        <th class="py-3">Acções</th>
                    </tr>
        </thead>

                    </thead>
                    <tbody id="customers">
                    {% for curso in cursos %}
                        <tr class="btn-reveal-trigger">
                            <td class="py-2">{{ curso.nomeCurso }}</td>
                            <td class="py-2">{{ curso.Coordinador }}</td>
                            <td class="py-2">{{ curso.email }}</td>
                            <td class="py-2">{{ curso.phone  }}</td>
                            <td>
                                <a href="{{ path('curso_show', {'id': curso.id}) }}" class="btn btn-sm btn-primary"><i class="fas fa-eye"></i></a>
                                <a href="{{ path('curso_edit', {'id': curso.id}) }}" class="btn btn-sm btn-secondary"><i class="fas fa-edit"></i></a>
                                <a href="{{path('curso_delete', {'id': curso.id})}}" class="btn btn-sm btn-danger"><i class="fas fa-trash"></i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5">no records found</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>



{% endblock %}

templates/curso/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Novo Curso{% endblock %}

{% block body %}
    <h3>Criar Novo Curso</h3>

    <div class="col-md-10">

        {{ include('curso/_form.html.twig') }}

    </div>
{% endblock %}

templates/curso/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mostrar Curso{% endblock %}

{% block body %}
<div class="col-sm-8">
    <div class="card">
        <div class="card-header">

            <h4> Curso {{ curso.nomeCurso}}</h4>
            <div class="card-body">
                <table class="table table-sm ">
                    <tbody>

                    <tbody>
            <tr>
                {{ include('curso/_delete_form.html.twig') }}
                <a href="{{ path('curso_index') }}" class="btn btn-sm btn-primary mr-2 ml-2"><i class="fas fa-list"></i>Voltar a Lista</a>
                <a href="{{ path('curso_edit', {'id': curso.id}) }}" class="btn btn-sm btn-secondary"><i class="fas fa-edit"></i>Editar</a>
            </tr>
            <tr>
                <th>Nome Curso</th>
                <td>{{ curso.nomeCurso}}</td>
            </tr>
            <tr>
                <th>Coordenador</th>
                <td>{{  curso.Coordinador  }}</td>
            </tr>
            <tr>
                <th>E-mail</th>
                <td>{{  curso.email   }}</td>
            </tr>
            <tr>
                <th>Telefone</th>
                <td>{{  curso.phone }}</td>
            </tr>

                    </tbody>
                </table>

            </div>
        </div>
    </div>

</div>



{% endblock %}